title: Okeke Divine Chidera
logo: IMG_1575.jpg
description: a deta Analyst with 10 years of experience. highly proficient with excel for the use of report automation or dat manipution and intelligence report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
